apiVersion: v1
kind: Pod
metadata:
  name: selector-demo
  labels:
    app.kubernetes.io/name: selector-demo
spec:
  nodeSelector: 
    env: lab
  containers:
  - name: selector-demo
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "100Mi"
        cpu: "300m"
    ports:
      - containerPort: 80
