apiVersion: v1
kind: Pod
metadata:
  name: qos-pod-burstable
  labels:
    app.kubernetes.io/name: qos-pod-burstable
spec:
  containers:
  - name: qos-pod-burstable
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "100Mi"
        cpu: "300m"
    ports:
      - containerPort: 80
