apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      name: ds-label
  template:
    metadata:
      labels:
        name: ds-label
    spec:
      containers:
      - name: daemonset-container
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
